// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5McrIpezaiZcWX-R8z72TXCphGt0gp_Y',
    appId: '1:209707554089:web:86b9bd26b90fb1c71f1338',
    messagingSenderId: '209707554089',
    projectId: 'to-do-list-299c5',
    authDomain: 'to-do-list-299c5.firebaseapp.com',
    storageBucket: 'to-do-list-299c5.firebasestorage.app',
    measurementId: 'G-7C4DE7GYEM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoQSsNlchIeVK7kY8o5TaKxVVXpVKZfH4',
    appId: '1:209707554089:android:8ffeac832d9f09b41f1338',
    messagingSenderId: '209707554089',
    projectId: 'to-do-list-299c5',
    storageBucket: 'to-do-list-299c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKAn6DQ9l4Ne3wVWdxt7yyUemm814iYqs',
    appId: '1:209707554089:ios:b8fdc448a54adfc01f1338',
    messagingSenderId: '209707554089',
    projectId: 'to-do-list-299c5',
    storageBucket: 'to-do-list-299c5.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5McrIpezaiZcWX-R8z72TXCphGt0gp_Y',
    appId: '1:209707554089:web:387c01ea3c39b26c1f1338',
    messagingSenderId: '209707554089',
    projectId: 'to-do-list-299c5',
    authDomain: 'to-do-list-299c5.firebaseapp.com',
    storageBucket: 'to-do-list-299c5.firebasestorage.app',
    measurementId: 'G-XQBFQCPT16',
  );
}
